---
---
# Source: curator/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  namespace: default
  labels:
    app: curator
    chart: curator-2.2.3
    release: curator
    heritage: Helm
data:
  action_file.yml:   |-
    ---
    actions:
      1:
        action: snapshot
        description: >-
          Snapshot indices with the default snapshot name pattern of
          'backup-%Y%m%d%H%M%S'.  Wait for the snapshot to complete.  Do not skip
          the repository filesystem access check.  Use the other options to create
          the snapshot.
        options:
          repository: es_snapshot
          # Leaving name blank will result in the default 'curator-%Y%m%d%H%M%S'
          name: backup-%Y%m%d%H%M%S
          ignore_unavailable: True
          ignore_empty_list: True
          include_global_state: True
          partial: False
          wait_for_completion: True
          skip_repo_fs_check: False
          disable_action: False
        filters:
          - filtertype: pattern
            kind: regex
            value: ".*"
      2:
        action: delete_snapshots
        description: >-
          Delete snapshots from the selected repository older than 2 days
          (based on creation_date), for 'backup-' prefixed snapshots.
        options:
          repository: es_snapshot
          disable_action: False
          ignore_empty_list: True
        filters:
          - filtertype: pattern
            kind: prefix
            value: backup-
            exclude:
          - filtertype: age
            source: creation_date
            direction: older
            unit: days
            unit_count: 2
  config.yml:   |-
    ---
    client:
      hosts:
        - opensearch-http-service
      port: 9200
      # url_prefix:
      use_ssl: False
      # certificate:
      # client_cert:
      # client_key:
      # ssl_no_validate: True
      # http_auth:
      # timeout: 30
      # master_only: False
    # logging:
    #   loglevel: INFO
    #   logfile:
    #   logformat: default
    #   blacklist: ['elasticsearch', 'urllib3']
---

# Source: curator/templates/cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
  namespace: default
  labels:
    app: curator
    chart: curator-2.2.3
    release: curator
    heritage: Helm
spec:
  schedule: "22 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: curator
        release: curator
    spec:
      template:
        metadata:
          labels:
            app: curator
            release: curator
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: acr-auth
          containers:
            - name: curator
              image: "episerver.azurecr.io/opensearch-curator:5.8.4"
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/es-curator

              command:
                - /curator/curator
              args: [ "--config", "/etc/es-curator/config.yml", "/etc/es-curator/action_file.yml" ]
              env:
              resources:
                {}
          securityContext:
            runAsUser: 16

