---
---
# Source: opensearch-data/templates/elasticsearchdataset.yaml
apiVersion: zalando.org/v1
kind: ElasticsearchDataSet
metadata:
  labels:
    application: elasticsearch
    role: data
    group: es-data
  name: es-data
  namespace: default
spec:
  scaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 55
    minIndexReplicas: 1
    maxIndexReplicas: 3
    minShardsPerNode: 1
    maxShardsPerNode: 600
    scaleUpCPUBoundary: 100
    scaleUpThresholdDurationSeconds: 10
    scaleUpCooldownSeconds: 10
    scaleDownCPUBoundary: 5
    scaleDownThresholdDurationSeconds: 10
    scaleDownCooldownSeconds: 10
    diskUsagePercentScaledownWatermark: 80
  template:
    metadata:
      labels:
        application: elasticsearch
        role: data
        group: es-data
    spec:
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
        - name: acr-auth
      serviceAccountName: es-operator
      containers:
      - name: elasticsearch
        securityContext:
          capabilities:
            add: [ "SYS_CHROOT" ]
        command:
          - bash
          - -c
          - |
            set -ex
            # Create keystore
            bin/opensearch-keystore create
            # Add azure-repository account/key
            [ ! -z "$STORAGE_ACCOUNT_NAME" ] && echo $STORAGE_ACCOUNT_NAME | bin/opensearch-keystore add --stdin azure.client.default.account
            [ ! -z "$STORAGE_ACCOUNT_KEY" ] && echo $STORAGE_ACCOUNT_KEY | bin/opensearch-keystore add --stdin azure.client.default.key
            env "node.attr.zone=$(</tmpConfig/es-zone)" /usr/share/opensearch/opensearch-docker-entrypoint.sh opensearch
        image: episerver.azurecr.io/episerver/find-elasticsearch:2.1.0-develop-47607
        imagePullPolicy: "Always"
        envFrom:
          - secretRef:
              name: cluster-secrets
        env:
        - name: "node.name"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "node.master"
          value: "false"
        - name: "node.ingest"
          value: "false"
        - name: "node.data"
          value: "true"
        - name: "OPENSEARCH_JAVA_OPTS"
          value: -Xms30G -Xmx30G
        - name: "cluster.name"
          value: $(CLUSTER_NAME)
        - name: "network.host"
          value: "0.0.0.0"
        - name: "discovery.seed_hosts"
          value: opensearch-discovery
        - name: "bootstrap.memory_lock"
          value: "false"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: STORAGE_ACCOUNT_KEY
          value: $(STORAGE_ACCOUNT_KEY)
        - name: STORAGE_ACCOUNT_NAME
          value: $(STORAGE_ACCOUNT_NAME)
        ports:
        - containerPort: 9300
          name: transport
        readinessProbe:
          tcpSocket:
            port: 9300
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
          limits:
            memory: 52Gi
          requests:
            memory: 52Gi
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: data
        - mountPath: /tmpConfig
          name: tmp
        - name: logs
          mountPath: /usr/share/opensearch/logs/log
        - name: cg-resources
          mountPath: /usr/share/opensearch/config/resources
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchLabels:
                    agentpool: esdata
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool # Replace this with corresponding worker node label's key
                    operator: In
                    values:
                      - "esdata" # Replace this with corresponding worker node label's value
      tolerations:
        - key: agentpool
          operator: Equal
          value: esdata
          effect: NoSchedule
      initContainers:
      - name: init-sysctl
        image: episerver.azurecr.io/busybox:1.27.2
        command:
          - sysctl
          - -w
          - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: fixmount
        command: [ 'sh', '-c', 'chown -R 1000:1000 /usr/share/opensearch/data' ]
        image: episerver.azurecr.io/busybox:1.27.2
        volumeMounts:
            - mountPath: /usr/share/opensearch/data
              name: data
      - name: set-ulimit
        image: episerver.azurecr.io/busybox:1.27.2
        command: [ "sh", "-c", "ulimit -n 65536" ]
        securityContext:
          privileged: true
      - name: get-zone
        image: episerver.azurecr.io/kubectl-jq:0.1
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - mountPath: /tmpConfig
            name: tmp
        command:
          - bash
          - -c
          - |
            set -ex
            ZONE=$(kubectl get node $NODE_NAME -o json | jq -r '.metadata.labels["failure-domain.beta.kubernetes.io/zone"]'); 
            echo $ZONE > /tmpConfig/es-zone
      volumes:
        - name: tmp
          emptyDir: { }
        - name: logs
          azureFile:
            secretName: fileshare-secrets
            shareName: "optiq-logs-prod"
            readOnly: false
        - name: cg-resources
          azureFile:
            secretName: fileshare-secrets
            shareName: "optiq-opensearch-resources"
            readOnly: true
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: managed-premium
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1000Gi

