---
---
# Source: container/templates/container-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tika
    app.kubernetes.io/instance: tika-prod
  name: tika-prod
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: tika
    app.kubernetes.io/instance: tika-prod
---

# Source: container/templates/container-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika-prod
  namespace: default
  labels:
    app.kubernetes.io/name: tika
    app.kubernetes.io/instance: tika-prod
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tika
      app.kubernetes.io/instance: tika-prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tika
        app.kubernetes.io/instance: tika-prod
    spec:
      containers:
      - name: tika
        image: episerver.azurecr.io/episerver/find-tika:1.20-develop-47608
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1.5"
            memory: "6Gi"
          requests:
            cpu: "1"
            memory: "4Gi"
        env:
        envFrom:
        - secretRef:
            name: cluster-secrets
        livenessProbe:
          httpGet:
            path: /tika
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: azure
          mountPath: /mnt/azure
      restartPolicy: Always
      imagePullSecrets:
      - name: acr-auth
      volumes:
      - name: azure
        azureFile:
          secretName: fileshare-secrets
          shareName: optiq-logs-prod
          readOnly: false
status: {}
---

# Source: container/templates/horizontal-autoscaler.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: tika
    app.kubernetes.io/instance: tika-prod
  name: tika-prod
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tika-prod
  minReplicas: 1
  maxReplicas: 250
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15

