---
---
# Source: index-rebuilder/templates/cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: index-rebuilder
  namespace: default
spec:
  schedule: "0 3 * * SAT"
  suspend: false
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: index-rebuilder
            app.kubernetes.io/name: index-rebuilder-0.1.0
            app.kubernetes.io/release_name: "index-rebuilder"
            app.kubernetes.io/version: "1.0"
        spec:
          restartPolicy: "Never"
          imagePullSecrets:
            - name: acr-auth
          containers:
            - name: index-rebuilder
              image: episerver.azurecr.io/index-rebuilder:latest
              imagePullPolicy: "Always"
              envFrom:
                - secretRef:
                    name: turnstile-secrets
              env:
              - name: ES_INGRESS
                value: "opensearch-http-service"
              - name: EPTS_KEY
                value: "$(KV_EPTS_KEY)"
              - name: EPTS_SECRET
                value: "$(KV_EPTS_SECRET)"
              - name: PROVISIONING_SERVICE
                value: "http://traefik-ingress-service"
              - name: LOG_DIR
                value: "/mnt/optiq-logs/"
              - name: RESIZE_MODE
                value: "True"
              - name: SHARD_SIZE
                value: "40"
              - name: INDEX_PATTERN
                value: "*"
              volumeMounts:
                - name: optiq-logs
                  mountPath: /mnt/optiq-logs
          volumes:
            - name: optiq-logs
              azureFile:
                secretName: fileshare-secrets
                shareName: "optiq-logs-prod"
                readOnly: false

