---
---
# Source: index-deleter/templates/cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: index-deleter
  namespace: default
spec:
  schedule: "0 5 * * *"
  suspend: false
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: index-deleter
            app.kubernetes.io/name: index-deleter-0.1.0
            app.kubernetes.io/release_name: "index-deleter"
            app.kubernetes.io/version: "1.0"
        spec:
          restartPolicy: "Never"
          imagePullSecrets:
            - name: acr-auth
          containers:
            - name: index-deleter
              image: episerver.azurecr.io/index-deleter:latest
              imagePullPolicy: "Always"
              envFrom:
                - secretRef:
                    name: turnstile-secrets
              env:
              - name: ES_INGRESS
                value: "opensearch-http-service"
              - name: LOG_DIR
                value: "/mnt/optiq-logs/"
              - name: INDEX_PATTERN
                value: "*"
              - name: TTL
                value: "30"
              volumeMounts:
                - name: optiq-logs
                  mountPath: /mnt/optiq-logs
          volumes:
            - name: optiq-logs
              azureFile:
                secretName: fileshare-secrets
                shareName: "optiq-logs-prod"
                readOnly: false

