---
---
# Source: ttl-docs/templates/cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ttl-docs
  namespace: default
spec:
  schedule: "0 2 * * *"
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ttl-docs
            app.kubernetes.io/name: ttl-docs-0.1.0
            app.kubernetes.io/release_name: "ttl-docs"
            app.kubernetes.io/version: "1.0"
        spec:
          restartPolicy: "Never"
          imagePullSecrets:
            - name: acr-auth
          containers:
            - name: ttl-docs
              image: episerver.azurecr.io/ttl-docs:latest
              imagePullPolicy: "Always"
              env:
              - name: ES_INGRESS
                value: "opensearch-http-service"
              - name: EXPIRE_DAYS
                value: "7"

